from manim import *

TEXT_COLOR = BLUE
TOP_TEXT_BUFFER = 0.5
BETWEEN_TEXT_BUFFER = 0.25

ANIMATION_TIME = 1
SHORT_DWELL_TIME = 0.6
LONG_DWELL_TIME = 1

PLUS_SCALE = 0.5
MINUS_SCALE = 0.12

INDICATE_COLOR = YELLOW
INDICATE_SCALE_FACTOR = 1.5

PL_CIRCLE_SIZE = 0.18
PL_FONT_SIZE = 22